In [1]:
import pandas as pd
data = pd.read_csv(r"bank-Information.csv")
data.sample(3)

age         job  marital  education default  balance housing loan  \
6333   34  management   single    primary      no      212      no   no   
7881   27  management   single   tertiary      no     2061     yes   no   
8577   37    services  married  secondary      no     1325      no   no   

      contact  day month  duration  campaign  pdays  previous poutcome   y  
6333  unknown   27   may        88         1     -1         0  unknown  no  
7881  unknown   30   may        72         3     -1         0  unknown  no  
8577  unknown    3   jun        72         3     -1         0  unknown  no

it is for test!  
thank you  


In [2]:
targeData = data[['age','day','duration','campaign','previous']]
targeData.dtypes

age         int64
day         int64
duration    int64
campaign    int64
previous    int64
dtype: object

In [3]:
values = targeData.values
values.shape

(45211, 5)

In [4]:
type(values)

numpy.ndarray

In [5]:
age = values[:,0]
age

array([58, 44, 33, ..., 72, 57, 37], dtype=int64)

In [6]:
import tensorflow as tf
tf.constant(1,dtype=tf.int64)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [7]:
a = tf.constant([1,2,4])
a.device

'/job:localhost/replica:0/task:0/device:GPU:0'

In [8]:
b = a.cpu()

Instructions for updating:
Use tf.identity instead.


In [9]:
b.device

'/job:localhost/replica:0/task:0/device:CPU:0'

In [10]:
a.ndim


1

In [11]:
b = tf.constant(2)
b.ndim

0

In [12]:
tf.rank(a)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [13]:
tf.convert_to_tensor(age,dtype=tf.int32)
tf.cast(a,tf.bool)
b = tf.Variable(a,name="xx")

In [14]:
tf.is_tensor(b)
c = tf.ones([2,3])
c

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

#### 第一次学习笔记
tensorflow 的数据类型 int , float , string , bool  
数据形式    标量 向量 矩阵 Tensor（张量）  
numpy -> tensor : tf.convert_to_tensor(numpy)  
tensor -> numpy : tf_v.numpy()  
计算引擎的切换：tf_v.cpu() tf_v.gpu()  
查看计算引擎：tf_v.device 
判断是否是tensor tf.is_tensor(tf_v)  
将变量赋给可求导的性质： tf.Variable(tf_v)  
tensor 类型转换：tf.cast(tf_v)

# tensor的创建

In [15]:
# 1.从numpy，列表装换
a = tf.convert_to_tensor(age,dtype=tf.int32)
tf.convert_to_tensor([1,2,4])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 4])>

In [16]:
# 2. tf.ones()、tf.zeros()、tf.ones_like()
tf.ones([2,4])
tf.ones_like(a)

<tf.Tensor: shape=(45211,), dtype=int32, numpy=array([1, 1, 1, ..., 1, 1, 1])>

In [17]:
# 3.tf.fill(num)
tf.fill([2,4],7)

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[7, 7, 7, 7],
       [7, 7, 7, 7]])>

In [18]:
# 4. tf.random.normal()
tf.random.normal([3,1],mean=9,stddev=34) #正态分布
tf.random.truncated_normal([3,5])#缺省正态分布
tf.random.uniform([1])
# mean 均值 stddev 方差

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.5167849], dtype=float32)>

In [19]:
tf.random.shuffle(a)#打散数据顺序
tf.range(30)

<tf.Tensor: shape=(30,), dtype=int32, numpy=
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])>

In [20]:
# 5 tf.constant()
tf.constant(1)
tf.one_hot(a,depth=4)

<tf.Tensor: shape=(45211, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       ...,
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

tensor 的索引 类似numpy

In [21]:
c = tf.random.normal([2,4,4,3])
c[1,...,2].shape

TensorShape([4, 4])

In [22]:
# tf.gather() 获取对应索引的数据
print(a)
tf.gather(a,[4,6,8])
tf.gather_nd(c,[[0,3,2],[1,2,1]])

tf.Tensor([58 44 33 ... 72 57 37], shape=(45211,), dtype=int32)


<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 0.9964216 , -0.67229414, -0.51058036],
       [ 0.73131406,  0.5801674 ,  0.35288784]], dtype=float32)>

In [23]:
a

<tf.Tensor: shape=(45211,), dtype=int32, numpy=array([58, 44, 33, ..., 72, 57, 37])>

In [24]:
c

<tf.Tensor: shape=(2, 4, 4, 3), dtype=float32, numpy=
array([[[[-1.6268964 , -2.1943343 ,  0.16371147],
         [ 0.11621902, -1.5499362 ,  0.04563286],
         [ 0.6226493 ,  1.6969109 ,  0.8755367 ],
         [-0.73203737,  0.37484327, -0.27630177]],

        [[-0.3344262 , -0.85191035, -2.3923826 ],
         [ 0.3114224 , -0.46554372,  0.31639242],
         [ 0.27826646,  0.79432124,  0.3077332 ],
         [-1.757361  , -0.22255206,  0.4695146 ]],

        [[ 0.03856628, -0.79253274,  0.77489245],
         [-0.05838043, -0.9735868 , -1.3132868 ],
         [-0.18005624,  0.3659029 , -0.20215082],
         [-0.44372323,  0.7908554 , -0.42326942]],

        [[ 0.5356755 ,  0.11547382,  0.4117342 ],
         [-0.6490017 , -0.56551456,  0.02401321],
         [ 0.9964216 , -0.67229414, -0.51058036],
         [ 1.1065115 ,  0.22338542, -1.0100578 ]]],


       [[[-0.27900982, -0.29620433, -0.3729558 ],
         [ 0.49740484, -2.459857  ,  0.44263387],
         [-1.713421  ,  1.6335077 , 

In [25]:
b  =tf.random.truncated_normal([3,2])
c = tf.random.truncated_normal([4,28,28])
d = tf.random.truncated_normal([4,28,28,3])

In [26]:
d.ndim,d.shape

(4, TensorShape([4, 28, 28, 3]))

tensor 的转置、合并维度、分解维度  

In [27]:
tf.reshape(d,[4,1,-1,3])#合并维度

<tf.Tensor: shape=(4, 1, 784, 3), dtype=float32, numpy=
array([[[[ 0.5885791 , -0.33980185,  0.8102548 ],
         [ 1.8819001 , -1.489278  , -0.10610389],
         [ 0.17691894,  0.69716513, -0.97397256],
         ...,
         [ 0.3833606 ,  0.5908952 , -0.6165003 ],
         [ 0.54759157, -0.6472085 , -1.8266704 ],
         [ 1.2111386 , -0.1268781 ,  0.8939801 ]]],


       [[[ 0.20543364,  0.51426053, -0.7491373 ],
         [-0.11517053,  0.10298555,  1.3760223 ],
         [-1.146881  , -1.09452   ,  0.09008617],
         ...,
         [ 1.5542593 ,  1.2437155 , -0.33828852],
         [ 1.1372588 , -0.62230504, -0.63943356],
         [ 0.70115626, -0.46441382, -0.4942298 ]]],


       [[[-0.6450653 ,  0.0805684 ,  1.2589258 ],
         [-0.24740686,  0.73125374, -0.52329594],
         [-0.47175342, -1.0022981 ,  0.4821777 ],
         ...,
         [-0.1965436 , -1.3237876 ,  0.48404643],
         [-0.13269305,  1.0323375 , -0.543635  ],
         [-0.32985532,  1.0745317 , -0.64694

In [28]:
tf.transpose(d,perm=[2,3,1,0]).shape #转置

TensorShape([28, 3, 28, 4])

In [29]:
tf.reshape(d,[4,14,2,28,3]).shape

TensorShape([4, 14, 2, 28, 3])

添加维度和删除维度

In [30]:
tf.expand_dims(c,axis=1).shape#添加一个维度为1的维度

TensorShape([4, 1, 28, 28])

In [31]:
tf.squeeze(tf.ones([1,2,3,1]),axis=0).shape#删除维度为1的维度

TensorShape([2, 3, 1])

broadcast

数学运算

In [32]:
b

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.6654062 , -1.254611  ],
       [-1.0557152 ,  1.2842488 ],
       [ 0.67325777,  0.18708399]], dtype=float32)>

In [33]:
b1 = tf.random.truncated_normal([2,4])

In [34]:
b1+b1,b1-b1,b1**2

(<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
 array([[ 0.09191087, -0.7498342 ,  0.546263  , -2.007958  ],
        [-1.4404923 , -3.2639353 , -3.064854  ,  0.3970158 ]],
       dtype=float32)>,
 <tf.Tensor: shape=(2, 4), dtype=float32, numpy=
 array([[0., 0., 0., 0.],
        [0., 0., 0., 0.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 4), dtype=float32, numpy=
 array([[2.1119020e-03, 1.4056283e-01, 7.4600808e-02, 1.0079738e+00],
        [5.1875448e-01, 2.6633184e+00, 2.3483324e+00, 3.9405387e-02]],
       dtype=float32)>)

In [35]:
tf.math.log(b),tf.exp(b),b@b1,b**(-1)*b,tf.exp(b)/tf.exp(tf.constant([[2,2],[2,2],[2,2]],dtype='float'))


(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.40735757,         nan],
        [        nan,  0.250174  ],
        [-0.39562702, -1.6761976 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[1.9452806 , 0.28518677],
        [0.34794348, 3.6119537 ],
        [1.9606141 , 1.2057285 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[ 0.93420774,  1.7980125 ,  2.1043432 , -0.91710407],
        [-0.97349113, -1.7000469 , -2.2563667 ,  1.3148494 ],
        [-0.10380667, -0.55773085, -0.10280466, -0.638799  ]],
       dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[0.99999994, 1.        ],
        [1.        , 1.        ],
        [1.        , 1.        ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[0.2632651 , 0.03859583],
        [0.04708903, 0.48882478],
        [0.26534027, 0.16317761]], dtype=float32)>)