In [8]:
import tensorflow as tf

梯度下降

In [9]:
# 计算梯度
x = tf.constant(-0.5)
w = tf.constant(0.1)
with tf.GradientTape(persistent=True) as tape:
    tape.watch([w,x])
    y = x*w
tape.gradient(y,x),tape.gradient(y,w)

(<tf.Tensor: shape=(), dtype=float32, numpy=0.1>,
 <tf.Tensor: shape=(), dtype=float32, numpy=-0.5>)

In [10]:
# sigmoid 函数求梯度
with tf.GradientTape() as tade:
    tade.watch([x])
    y=tf.sigmoid(x)
tade.gradient(y,[x])

[<tf.Tensor: shape=(), dtype=float32, numpy=0.23500371>]

In [11]:
# tanh 函数求梯度
with tf.GradientTape() as tade:
    tade.watch([x])
    y = tf.tanh(x)
tade.gradient(y,x) 

<tf.Tensor: shape=(), dtype=float32, numpy=0.7864477>

In [12]:
# relu 函数求梯度
with tf.GradientTape(persistent=True) as tade:
    tade.watch([x])
    y = tf.nn.relu(x)
    g = tf.nn.leaky_relu(x)
    print(g)
tade.gradient(y,x) ,tade.gradient(g,x)

tf.Tensor(-0.1, shape=(), dtype=float32)


(<tf.Tensor: shape=(), dtype=float32, numpy=0.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.2>)

In [16]:
# 分类问题：softmax 求梯度
a = tf.constant([0.1,0.1,0.2,0.2,0.4])
with tf.GradientTape() as tade:
    tade.watch([a])
    y = tf.nn.softmax(a)
    print(y)
tade.gradient(y,a) 

tf.Tensor([0.17984962 0.17984962 0.19876459 0.19876459 0.24277161], shape=(5,), dtype=float32)


<tf.Tensor: shape=(5,), dtype=float32, numpy=array([0., 0., 0., 0., 0.], dtype=float32)>

In [20]:
# 交叉熵求梯度
x = tf.random.normal([2,10],mean=10.,stddev=12.)
w = tf.random.normal([10,3])
b = tf.zeros([3])
y = tf.constant([2,1])
with tf.GradientTape() as tade:
    tade.watch([w,b])
    h = x@w+b
    out = tf.nn.softmax(h)
    out = tf.reduce_mean(tf.losses.categorical_crossentropy(tf.one_hot(y,3),out))
tade.gradient(out,[w,b])

[<tf.Tensor: shape=(10, 3), dtype=float32, numpy=
 array([[ 3.29934191e-10,  1.38757430e-04, -1.38757750e-04],
        [ 3.65298541e-10,  1.53630288e-04, -1.53630652e-04],
        [ 8.23584922e-10,  3.46367655e-04, -3.46368470e-04],
        [ 4.34392161e-10,  1.82688382e-04, -1.82688818e-04],
        [ 5.08518505e-10,  2.13863023e-04, -2.13863532e-04],
        [-1.11797238e-10, -4.70175510e-05,  4.70176637e-05],
        [ 2.87282170e-10,  1.20819655e-04, -1.20819939e-04],
        [ 2.47059994e-11,  1.03903785e-05, -1.03904031e-05],
        [ 4.09973756e-11,  1.72418950e-05, -1.72419350e-05],
        [ 1.43319689e-10,  6.02746586e-05, -6.02748041e-05]], dtype=float32)>,
 <tf.Tensor: shape=(3,), dtype=float32, numpy=array([ 2.5620147e-11,  1.0774833e-05, -1.0774858e-05], dtype=float32)>]